# Generated by Django 5.0.7 on 2024-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonAPI",
            "0002_orderitems_quantity_orders_customer_orders_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitems",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
    ]
