# Generated by Django 5.0.7 on 2024-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonAPI",
            "0004_rename_cartitems_cartitem_rename_categories_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Assigned"),
                    (2, "En route"),
                    (3, "Delivered"),
                ],
                default=0,
            ),
        ),
    ]
